import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // const year = new Date().getFullYear();

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <header className="bg-white shadow p-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">Zac Clifton</h1>
            <nav className="space-x-4">
              <a href="/#about" className="text-gray-600 hover:text-gray-900">About</a>
              <a href="/#projects" className="text-gray-600 hover:text-gray-900">Projects</a>
              <a href="/#contact" className="text-gray-600 hover:text-gray-900">Contact</a>
            </nav>
          </div>
        </header>
        <main className="container mx-auto py-8">{children}</main>
        {/*<footer className="bg-gray-900 text-white text-center py-4">*/}
        {/*  <p>© {year} Zac Clifton. All rights reserved.</p>*/}
        {/*</footer>*/}
      </body>
    </html>
  );
}
